services:
  - type: web
    name: puppeteer-app
    env: node
    buildCommand: npm install
    startCommand: node index.js
    buildpacks:
      - url: https://github.com/jontewks/puppeteer-heroku-buildpack.git
    envVars:
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
